name: Scheduled Health Check
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write
on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minute

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Run Health Check Script
        run: bash ./health-check.sh
